/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

//
// curl http://localhost:8080/poka/score -X POST -H "Content-Type: application/json" -d '{"cards": "S1 S2 S3 S4 S5"}'
//
//curl http://localhost:8080/poka/scores -X POST -H "Content-Type: application/json" -d '{"cards": ["S1 S2 S3 S4 S5"]}'
//
public class AppTest {
    @Test
    public void testAppHasAGreeting() {
       // App classUnderTest = new App();
       assertNotNull("app should have a greeting", "");
    }
}
